### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [dkrivoruchko/ScreenStream#227]
4.0.1 is live I see, plenty of changes, webrtc stuff

But, updated recipe:
```
  - versionName: 4.0.1
    versionCode: 40001
    commit: 3ee6ae213ac6408da198d269818035fda0145f46
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
      - chmod -R 777 /opt/android-sdk
    gradle:
      - firebasefree
    srclibs:
      - Material-Dialogs@3.3.0
    rm:
      - app/libs/bottomsheets-release.aar
    prebuild:
      - sed -i -e '/gms/d; /firebase/d' ../build.gradle.kts
      - sed -i -e '/google-services/d; /id("com.google.firebase.crashlytics")/d; /CrashlyticsExtension/,+2d;
        /SIGNALING_SERVER/d; /CLOUD_PROJECT/d' build.gradle.kts
      - sed -i -e '/play/d' ../webrtc/build.gradle.kts
      - pushd $$Material-Dialogs$$
      - sed -i -e '241d' bottomsheets/src/main/java/com/afollestad/materialdialogs/bottomsheets/BottomSheet.kt
    build:
      - pushd $$Material-Dialogs$$
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 gradle bottomsheets:assembleRelease
      - popd
      - cp $$Material-Dialogs$$/bottomsheets/build/outputs/aar/bottomsheets-release.aar
        libs/
```
...fails with
```
> Task :webrtc:compileReleaseKotlin
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:5:12 Unresolved reference: google
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:6:12 Unresolved reference: google
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:9:27 Unresolved reference: tasks
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:13:52 Unresolved reference: StandardIntegrityManager
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:14:50 Unresolved reference: StandardIntegrityManager
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:18:36 Unresolved reference: IntegrityManagerFactory
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:25:17 Unresolved reference: StandardIntegrityManager
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:36:13 Unresolved reference: StandardIntegrityManager
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/StandardIntegrityManagerWrapper.kt:42:39 Unresolved reference: it
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:4:12 Unresolved reference: google
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:5:12 Unresolved reference: google
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:31:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:32:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:33:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:34:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:35:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:36:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:37:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:42:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:43:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:44:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:49:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:50:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:51:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:56:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:57:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:58:13 Unresolved reference: StandardIntegrityErrorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:61:21 Unresolved reference: StandardIntegrityException
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:124:26 Unresolved reference: StandardIntegrityException
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:124:62 Unresolved reference: errorCode
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:139:26 Unresolved reference: StandardIntegrityException
e: file:///home/vagrant/build/info.dvkr.screenstream/webrtc/src/main/kotlin/info/dvkr/screenstream/webrtc/internal/PlayIntegrity.kt:139:62 Unresolved reference: errorCode

> Task :webrtc:compileReleaseKotlin FAILED
> Task :app:collectFirebaseFreeReleaseDependencies
> Task :app:processFirebaseFreeReleaseManifestForPackage
> Task :app:bundleFirebaseFreeReleaseResources
> Task :mjpeg:compileReleaseKotlin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webrtc:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
...because your webrtc component lib is dependent of proprietary Google lib

**Comment by licaon-kter** [comment]
> 4.x is not yet ready for full rollout. It's in beta test and code is in separate brunch (not “master”)

:shrug: https://github.com/dkrivoruchko/ScreenStream/releases/tag/4.0.1

> Not sure if F-Droid version will support WebRTC at all.

We have plenty of webrtc apps that don't depend on Google libs, how come?

**Comment by dkrivoruchko** [comment]
It's just a tag. It's not a release: https://github.com/dkrivoruchko/ScreenStream/releases
I removed the tag.

To protect signaling server, [Google Play Integrity](https://developer.android.com/google/play/integrity) lib is used.
If it's ok to use it for F-Droid builds, then WebRTC module will be eventually available for F-Droid builds too.

**Comment by licaon-kter** [comment]
Ah, signaling server? You mean we'd need to add `NonFreeNet` to your app too :( 

But yeah, no Google proprietary libs can be used... :-1: 

Then what's the path forward? A webrtc-less app or no more updates?

**Comment by dkrivoruchko** [comment]
Not sure if I got correctly about `NonFreeNet`.

This app to run WebRTC module use signaling server also written by me https://github.com/dkrivoruchko/ScreenStreamWeb
It's hosted on Heroku (non-free) and published via Cloudflare (non-free) along with web client.
To protect this singling server, Android app uses [Google Play Integrity](https://developer.android.com/google/play/integrity) lib and there is no alternative. At least known to me.

Cloudflare [Turnstile](https://developers.cloudflare.com/turnstile/) is used for web clients.

If there is no way to make WebRTC module work within F-Droid requirements, then 4.x builds for F-Droid will be only with current MJPEG module only once it's ready.

**Comment by licaon-kter** [comment]
> then 4.x builds for F-Droid will be only with current MJPEG module only once it's ready.

:+1:

**Comment by licaon-kter** [comment]
after the switch to kotlin we need to update the recipe, disabled for now https://gitlab.com/fdroid/fdroiddata/-/commit/9aefce583ed5489e30bb40a7382a7166f54da950

I started working on it locally, brb

**Comment by licaon-kter** [comment]
This recipe:
```
  - versionName: 4.0.30
    versionCode: 40030
    commit: 079ff11fe69836328426d179beddfa1449f1c1ea
    subdir: app
    sudo:
      - chmod -R 777 /opt/android-sdk
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    gradle:
      - firebasefree
    srclibs:
      - Material-Dialogs@3.3.0
    rm:
      - app/libs/bottomsheets-release.aar
      - mjpeg/libs/bottomsheets-release.aar
    prebuild:
      - sed -i -e '/google.services/d' -e '/firebase.crashlytics/d' -e '/googleServices/d'
        -e '/firebaseCrashlytics/d' ../build.gradle.kts
      - sed -i -e '/googleServices/d' -e '/firebaseCrashlytics/d' -e '/buildtools.gradle.CrashlyticsExtension/,+2d'
        -e '/firebaseImplementation/d' build.gradle.kts ../gradle/libs.versions.toml
      - sed -i -e '/google-/d' -e '/play-/d' -e '/firebase-/d' ../gradle/libs.versions.toml
      - sed -i -e '/:webrtc/d' ../settings.gradle.kts
    build:
      - pushd $$Material-Dialogs$$
      - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - gradle bottomsheets:assembleRelease
      - popd
      - cp $$Material-Dialogs$$/bottomsheets/build/outputs/aar/bottomsheets-release.aar
        libs/
      - cp $$Material-Dialogs$$/bottomsheets/build/outputs/aar/bottomsheets-release.aar
        ../mjpeg/libs/
```

fails: [info.dvkr.screenstream_40030.log.gz](https://github.com/dkrivoruchko/ScreenStream/files/13875855/info.dvkr.screenstream_40030.log.gz)

What am I missing ?
